// Motorcycle data with detailed information
const motorcyclesData = {
    // Honda
    'cbr1000rr-r-fireblade': {
        brand: 'Honda',
        name: 'CBR1000RR-R Fireblade',
        origin: 'Japan',
        category: 'Superbike',
        engine: '999cc inline-4',
        power: '217 HP',
        torque: '113 Nm',
        weight: '201 kg',
        topSpeed: '299 km/h',
        price: '$28,500',
        description: 'The ultimate superbike from Honda, featuring MotoGP-derived technology and race-winning performance.',
        features: ['Ride-by-Wire Throttle', 'Cornering ABS', 'Quick Shifter', 'Öhlins Electronic Suspension'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=CBR1000RR-R'
    },
    'africa-twin': {
        brand: 'Honda',
        name: 'Africa Twin',
        origin: 'Japan',
        category: 'Adventure',
        engine: '1084cc parallel-twin',
        power: '101 HP',
        torque: '105 Nm',
        weight: '226 kg',
        topSpeed: '190 km/h',
        price: '$14,500',
        description: 'Legendary adventure bike designed for both on-road and off-road excellence.',
        features: ['DCT Transmission', 'Cruise Control', 'Apple CarPlay', 'LED Lighting'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Africa+Twin'
    },
    'gold-wing': {
        brand: 'Honda',
        name: 'Gold Wing',
        origin: 'Japan',
        category: 'Touring',
        engine: '1833cc flat-6',
        power: '126 HP',
        torque: '170 Nm',
        weight: '383 kg',
        topSpeed: '210 km/h',
        price: '$23,800',
        description: 'The ultimate luxury touring motorcycle with unmatched comfort and technology.',
        features: ['7-Speed DCT', 'Navigation System', 'Heated Seats', 'Apple CarPlay'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Gold+Wing'
    },
    'cb650r': {
        brand: 'Honda',
        name: 'CB650R',
        origin: 'Japan',
        category: 'Naked',
        engine: '649cc inline-4',
        power: '94 HP',
        torque: '64 Nm',
        weight: '202 kg',
        topSpeed: '210 km/h',
        price: '$8,700',
        description: 'Neo Sports Café styling meets inline-four performance in this modern naked bike.',
        features: ['Slipper Clutch', 'LCD Display', 'LED Lights', 'ABS'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=CB650R'
    },

    // Yamaha
    'yzf-r1': {
        brand: 'Yamaha',
        name: 'YZF-R1',
        origin: 'Japan',
        category: 'Superbike',
        engine: '998cc inline-4',
        power: '200 HP',
        torque: '112.4 Nm',
        weight: '199 kg',
        topSpeed: '299 km/h',
        price: '$17,399',
        description: 'MotoGP technology in a street-legal superbike with crossplane crankshaft.',
        features: ['IMU Electronics', 'Quick Shifter', 'Launch Control', 'Slide Control'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=YZF-R1'
    },
    'mt-09': {
        brand: 'Yamaha',
        name: 'MT-09',
        origin: 'Japan',
        category: 'Naked',
        engine: '889cc inline-3',
        power: '119 HP',
        torque: '93 Nm',
        weight: '189 kg',
        topSpeed: '220 km/h',
        price: '$9,399',
        description: 'The ultimate hyper-naked with triple-cylinder excitement and cutting-edge electronics.',
        features: ['6-Axis IMU', 'Ride Modes', 'TFT Display', 'Quick Shifter'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=MT-09'
    },
    'tenere-700': {
        brand: 'Yamaha',
        name: 'Ténéré 700',
        origin: 'Japan',
        category: 'Adventure',
        engine: '689cc parallel-twin',
        power: '72 HP',
        torque: '68 Nm',
        weight: '204 kg',
        topSpeed: '175 km/h',
        price: '$10,299',
        description: 'Lightweight adventure bike built for serious off-road capability.',
        features: ['Rally-Inspired', 'ABS', 'Long Travel Suspension', 'Off-Road Ready'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Tenere+700'
    },
    'niken': {
        brand: 'Yamaha',
        name: 'NIKEN',
        origin: 'Japan',
        category: 'Sport Touring',
        engine: '847cc inline-3',
        power: '115 HP',
        torque: '87.5 Nm',
        weight: '263 kg',
        topSpeed: '210 km/h',
        price: '$17,099',
        description: 'Revolutionary three-wheel design offering unmatched cornering confidence.',
        features: ['LMW Technology', 'TFT Display', 'Cruise Control', 'Traction Control'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=NIKEN'
    },

    // Ducati
    'panigale-v4': {
        brand: 'Ducati',
        name: 'Panigale V4',
        origin: 'Italy',
        category: 'Superbike',
        engine: '1103cc V4',
        power: '214 HP',
        torque: '124 Nm',
        weight: '198 kg',
        topSpeed: '305 km/h',
        price: '$24,995',
        description: 'Italian superbike excellence with MotoGP-derived V4 engine and stunning design.',
        features: ['Cornering ABS', 'DTC EVO', 'DWC EVO', 'Öhlins Suspension'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Panigale+V4'
    },
    'monster': {
        brand: 'Ducati',
        name: 'Monster',
        origin: 'Italy',
        category: 'Naked',
        engine: '937cc L-twin',
        power: '111 HP',
        torque: '93 Nm',
        weight: '188 kg',
        topSpeed: '210 km/h',
        price: '$11,895',
        description: 'Iconic naked bike with Italian styling and Testastretta engine.',
        features: ['Ride Modes', 'TFT Display', 'LED Lights', 'Quick Shifter'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Monster'
    },
    'multistrada-v4': {
        brand: 'Ducati',
        name: 'Multistrada V4',
        origin: 'Italy',
        category: 'Adventure',
        engine: '1158cc V4',
        power: '170 HP',
        torque: '125 Nm',
        weight: '218 kg',
        topSpeed: '270 km/h',
        price: '$23,295',
        description: 'Sport-touring adventure bike with V4 Granturismo engine and advanced electronics.',
        features: ['Radar Technology', 'Adaptive Cruise', 'Semi-Active Suspension', 'V4 Engine'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Multistrada+V4'
    },
    'scrambler': {
        brand: 'Ducati',
        name: 'Scrambler',
        origin: 'Italy',
        category: 'Scrambler',
        engine: '803cc L-twin',
        power: '73 HP',
        torque: '66.2 Nm',
        weight: '189 kg',
        topSpeed: '180 km/h',
        price: '$9,395',
        description: 'Retro-styled bike with modern technology and Italian charm.',
        features: ['Ride by Wire', 'ABS', 'LED Lights', 'LCD Display'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Scrambler'
    },

    // BMW
    's1000rr': {
        brand: 'BMW',
        name: 'S1000RR',
        origin: 'Germany',
        category: 'Superbike',
        engine: '999cc inline-4',
        power: '205 HP',
        torque: '113 Nm',
        weight: '197 kg',
        topSpeed: '299 km/h',
        price: '$17,895',
        description: 'German precision engineering meets superbike performance.',
        features: ['ShiftCam Technology', 'Dynamic Traction Control', 'ABS Pro', 'Launch Control'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=S1000RR'
    },
    'r1250gs': {
        brand: 'BMW',
        name: 'R1250GS',
        origin: 'Germany',
        category: 'Adventure',
        engine: '1254cc boxer-twin',
        power: '136 HP',
        torque: '143 Nm',
        weight: '249 kg',
        topSpeed: '210 km/h',
        price: '$18,995',
        description: 'The world\'s most popular adventure bike with boxer engine.',
        features: ['ShiftCam', 'Dynamic ESA', 'Connectivity', 'TFT Display'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=R1250GS'
    },
    'm1000rr': {
        brand: 'BMW',
        name: 'M1000RR',
        origin: 'Germany',
        category: 'Superbike',
        engine: '999cc inline-4',
        power: '212 HP',
        torque: '113 Nm',
        weight: '192 kg',
        topSpeed: '306 km/h',
        price: '$33,995',
        description: 'BMW\'s first M-branded motorcycle with race-ready technology.',
        features: ['M Carbon Wheels', 'M GPS Lap Trigger', 'M Winglets', 'M ABS'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=M1000RR'
    },
    'f900r': {
        brand: 'BMW',
        name: 'F900R',
        origin: 'Germany',
        category: 'Naked',
        engine: '895cc parallel-twin',
        power: '105 HP',
        torque: '92 Nm',
        weight: '211 kg',
        topSpeed: '220 km/h',
        price: '$9,495',
        description: 'Dynamic roadster with sporty character and everyday usability.',
        features: ['Ride Modes', 'ABS Pro', 'TFT Display', 'LED Lights'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=F900R'
    },

    // Kawasaki
    'ninja-h2': {
        brand: 'Kawasaki',
        name: 'Ninja H2',
        origin: 'Japan',
        category: 'Superbike',
        engine: '998cc inline-4 supercharged',
        power: '228 HP',
        torque: '141.7 Nm',
        weight: '238 kg',
        topSpeed: '336 km/h',
        price: '$29,500',
        description: 'Supercharged hyperbike pushing the boundaries of performance.',
        features: ['Supercharged Engine', 'Carbon Fiber', 'Launch Control', 'Quick Shifter'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Ninja+H2'
    },
    'z900': {
        brand: 'Kawasaki',
        name: 'Z900',
        origin: 'Japan',
        category: 'Naked',
        engine: '948cc inline-4',
        power: '125 HP',
        torque: '98.6 Nm',
        weight: '210 kg',
        topSpeed: '230 km/h',
        price: '$8,999',
        description: 'Aggressive naked bike with inline-four punch and sharp handling.',
        features: ['Sugomi Design', 'TFT Display', 'Traction Control', 'ABS'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Z900'
    },
    'versys-1000': {
        brand: 'Kawasaki',
        name: 'Versys 1000',
        origin: 'Japan',
        category: 'Adventure',
        engine: '1043cc inline-4',
        power: '120 HP',
        torque: '102 Nm',
        weight: '250 kg',
        topSpeed: '210 km/h',
        price: '$13,099',
        description: 'Sport-adventure bike with inline-four power and touring comfort.',
        features: ['KQS Quick Shifter', 'KIBS ABS', 'Cruise Control', 'TFT Display'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Versys+1000'
    },
    'zx-10r': {
        brand: 'Kawasaki',
        name: 'ZX-10R',
        origin: 'Japan',
        category: 'Superbike',
        engine: '998cc inline-4',
        power: '200 HP',
        torque: '114.9 Nm',
        weight: '206 kg',
        topSpeed: '299 km/h',
        price: '$16,599',
        description: 'World Superbike-winning technology in a production superbike.',
        features: ['Kawasaki Cornering Management', 'Launch Control', 'TFT Display', 'Quick Shifter'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=ZX-10R'
    },

    // Suzuki
    'hayabusa': {
        brand: 'Suzuki',
        name: 'Hayabusa',
        origin: 'Japan',
        category: 'Sport',
        engine: '1340cc inline-4',
        power: '187 HP',
        torque: '150 Nm',
        weight: '264 kg',
        topSpeed: '299 km/h',
        price: '$18,599',
        description: 'Legendary speed icon with third-generation refinement and technology.',
        features: ['Ride Modes', 'Launch Control', 'TFT Display', 'Cruise Control'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Hayabusa'
    },
    'gsx-r1000': {
        brand: 'Suzuki',
        name: 'GSX-R1000',
        origin: 'Japan',
        category: 'Superbike',
        engine: '999cc inline-4',
        power: '202 HP',
        torque: '117.6 Nm',
        weight: '202 kg',
        topSpeed: '299 km/h',
        price: '$14,799',
        description: 'Race-proven superbike with MotoGP technology and aggressive performance.',
        features: ['Bi-Directional Quick Shifter', 'Launch Control', 'Cornering ABS', 'Motion Track'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=GSX-R1000'
    },
    'v-strom-1050': {
        brand: 'Suzuki',
        name: 'V-Strom 1050',
        origin: 'Japan',
        category: 'Adventure',
        engine: '1037cc V-twin',
        power: '107 HP',
        torque: '100 Nm',
        weight: '236 kg',
        topSpeed: '200 km/h',
        price: '$14,299',
        description: 'Versatile adventure bike with V-twin character and touring comfort.',
        features: ['Cruise Control', 'Traction Control', 'TFT Display', 'LED Lights'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=V-Strom+1050'
    },
    'katana': {
        brand: 'Suzuki',
        name: 'Katana',
        origin: 'Japan',
        category: 'Sport',
        engine: '999cc inline-4',
        power: '150 HP',
        torque: '108 Nm',
        weight: '215 kg',
        topSpeed: '260 km/h',
        price: '$13,199',
        description: 'Legendary name returns with modern performance and iconic styling.',
        features: ['Traction Control', 'LCD Display', 'LED Lights', 'ABS'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Katana'
    },

    // KTM
    '1290-super-duke-r': {
        brand: 'KTM',
        name: '1290 Super Duke R',
        origin: 'Austria',
        category: 'Naked',
        engine: '1301cc V-twin',
        power: '180 HP',
        torque: '140 Nm',
        weight: '189 kg',
        topSpeed: '290 km/h',
        price: '$19,499',
        description: 'The Beast - raw power and aggressive styling define this Austrian supernaked.',
        features: ['TFT Display', 'Cornering ABS', 'Traction Control', 'Quick Shifter'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=1290+Super+Duke+R'
    },
    '890-duke': {
        brand: 'KTM',
        name: '890 Duke',
        origin: 'Austria',
        category: 'Naked',
        engine: '889cc parallel-twin',
        power: '115 HP',
        torque: '92 Nm',
        weight: '169 kg',
        topSpeed: '240 km/h',
        price: '$11,999',
        description: 'Sharp-edged streetfighter with razor-precise handling.',
        features: ['Ride Modes', 'TFT Display', 'Quick Shifter', 'LED Lights'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=890+Duke'
    },
    '1290-super-adventure': {
        brand: 'KTM',
        name: '1290 Super Adventure',
        origin: 'Austria',
        category: 'Adventure',
        engine: '1301cc V-twin',
        power: '160 HP',
        torque: '138 Nm',
        weight: '249 kg',
        topSpeed: '220 km/h',
        price: '$19,799',
        description: 'Travel the world with sport bike performance in adventure bike clothing.',
        features: ['Adaptive Cruise Control', 'Cornering ABS', 'Semi-Active Suspension', 'Connectivity'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=1290+Super+Adventure'
    },
    'rc-390': {
        brand: 'KTM',
        name: 'RC 390',
        origin: 'Austria',
        category: 'Sport',
        engine: '373cc single',
        power: '43 HP',
        torque: '37 Nm',
        weight: '172 kg',
        topSpeed: '167 km/h',
        price: '$5,799',
        description: 'Entry-level sport bike with race-ready attitude and sharp handling.',
        features: ['Ride by Wire', 'TFT Display', 'Superbike Riding Position', 'ABS'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=RC+390'
    },

    // Harley-Davidson
    'pan-america-1250': {
        brand: 'Harley-Davidson',
        name: 'Pan America 1250',
        origin: 'USA',
        category: 'Adventure',
        engine: '1252cc V-twin',
        power: '150 HP',
        torque: '128 Nm',
        weight: '258 kg',
        topSpeed: '200 km/h',
        price: '$17,319',
        description: 'Harley\'s first adventure bike brings American muscle to the dirt.',
        features: ['Adaptive Ride Height', 'Cornering ABS', 'Traction Control', 'TFT Display'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Pan+America+1250'
    },
    'sportster-s': {
        brand: 'Harley-Davidson',
        name: 'Sportster S',
        origin: 'USA',
        category: 'Cruiser',
        engine: '1252cc V-twin',
        power: '121 HP',
        torque: '127 Nm',
        weight: '228 kg',
        topSpeed: '200 km/h',
        price: '$15,999',
        description: 'Modern muscle cruiser with Revolution Max engine and premium components.',
        features: ['TFT Display', 'LED Lighting', 'Adjustable Suspension', 'Cornering ABS'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Sportster+S'
    },
    'road-glide': {
        brand: 'Harley-Davidson',
        name: 'Road Glide',
        origin: 'USA',
        category: 'Touring',
        engine: '1923cc V-twin',
        power: '105 HP',
        torque: '170 Nm',
        weight: '388 kg',
        topSpeed: '180 km/h',
        price: '$23,999',
        description: 'Iconic bagger with frame-mounted fairing for stable highway cruising.',
        features: ['BOOM! Audio', 'Navigation', 'Cruise Control', 'LED Lights'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Road+Glide'
    },
    'fat-boy': {
        brand: 'Harley-Davidson',
        name: 'Fat Boy',
        origin: 'USA',
        category: 'Cruiser',
        engine: '1868cc V-twin',
        power: '93 HP',
        torque: '155 Nm',
        weight: '317 kg',
        topSpeed: '170 km/h',
        price: '$20,999',
        description: 'Muscular cruiser with solid disc wheels and unmistakable presence.',
        features: ['Milwaukee-Eight Engine', 'LED Lighting', 'ABS', 'Electronic Cruise Control'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Fat+Boy'
    },

    // Triumph
    'speed-triple': {
        brand: 'Triumph',
        name: 'Speed Triple',
        origin: 'UK',
        category: 'Naked',
        engine: '1160cc inline-3',
        power: '177 HP',
        torque: '125 Nm',
        weight: '199 kg',
        topSpeed: '260 km/h',
        price: '$18,500',
        description: 'British triple-cylinder brutality with iconic styling and modern tech.',
        features: ['Öhlins Suspension', 'Brembo Brakes', 'TFT Display', 'Quick Shifter'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Speed+Triple'
    },
    'tiger-1200': {
        brand: 'Triumph',
        name: 'Tiger 1200',
        origin: 'UK',
        category: 'Adventure',
        engine: '1160cc inline-3',
        power: '150 HP',
        torque: '130 Nm',
        weight: '255 kg',
        topSpeed: '220 km/h',
        price: '$18,995',
        description: 'Versatile adventure tourer with triple power and go-anywhere capability.',
        features: ['Adaptive Cruise', 'Semi-Active Suspension', 'Cornering ABS', 'TFT Display'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Tiger+1200'
    },
    'bonneville': {
        brand: 'Triumph',
        name: 'Bonneville',
        origin: 'UK',
        category: 'Classic',
        engine: '900cc parallel-twin',
        power: '65 HP',
        torque: '80 Nm',
        weight: '203 kg',
        topSpeed: '180 km/h',
        price: '$10,995',
        description: 'Timeless British classic with modern reliability and authentic character.',
        features: ['Ride by Wire', 'ABS', 'Traction Control', 'LED Lights'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Bonneville'
    },
    'rocket-3': {
        brand: 'Triumph',
        name: 'Rocket 3',
        origin: 'UK',
        category: 'Cruiser',
        engine: '2458cc inline-3',
        power: '165 HP',
        torque: '221 Nm',
        weight: '291 kg',
        topSpeed: '220 km/h',
        price: '$23,500',
        description: 'World\'s largest production motorcycle engine with brutal torque.',
        features: ['TFT Display', 'Ride Modes', 'Traction Control', 'Cruise Control'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Rocket+3'
    },

    // Royal Enfield
    'himalayan': {
        brand: 'Royal Enfield',
        name: 'Himalayan',
        origin: 'India',
        category: 'Adventure',
        engine: '411cc single',
        power: '24 HP',
        torque: '32 Nm',
        weight: '199 kg',
        topSpeed: '125 km/h',
        price: '$5,149',
        description: 'Affordable adventure bike built for the mountains and beyond.',
        features: ['Long Travel Suspension', 'Tripper Navigation', 'ABS', 'Windscreen'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Himalayan'
    },
    'continental-gt': {
        brand: 'Royal Enfield',
        name: 'Continental GT',
        origin: 'India',
        category: 'Cafe Racer',
        engine: '648cc parallel-twin',
        power: '47 HP',
        torque: '52 Nm',
        weight: '198 kg',
        topSpeed: '160 km/h',
        price: '$6,299',
        description: 'Modern cafe racer with classic British styling and twin-cylinder power.',
        features: ['Slipper Clutch', 'ABS', 'USD Forks', 'Clip-On Handlebars'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Continental+GT'
    },
    'meteor-350': {
        brand: 'Royal Enfield',
        name: 'Meteor 350',
        origin: 'India',
        category: 'Cruiser',
        engine: '349cc single',
        power: '20.2 HP',
        torque: '27 Nm',
        weight: '191 kg',
        topSpeed: '115 km/h',
        price: '$4,399',
        description: 'Easy-going cruiser with retro charm and modern reliability.',
        features: ['Tripper Navigation', 'LED Lights', 'Low Seat Height', 'Bluetooth'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Meteor+350'
    },
    'hunter-350': {
        brand: 'Royal Enfield',
        name: 'Hunter 350',
        origin: 'India',
        category: 'Roadster',
        engine: '349cc single',
        power: '20.2 HP',
        torque: '27 Nm',
        weight: '181 kg',
        topSpeed: '114 km/h',
        price: '$4,299',
        description: 'Urban roadster with nimble handling and accessible performance.',
        features: ['Lightweight', 'Low Seat Height', 'LED Lights', 'Digital Console'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Hunter+350'
    },

    // Aprilia
    'rsv4': {
        brand: 'Aprilia',
        name: 'RSV4',
        origin: 'Italy',
        category: 'Superbike',
        engine: '1099cc V4',
        power: '217 HP',
        torque: '125 Nm',
        weight: '199 kg',
        topSpeed: '305 km/h',
        price: '$19,999',
        description: 'Race-bred Italian superbike with V4 power and advanced electronics.',
        features: ['APRC Suite', 'Semi-Active Suspension', 'Quick Shifter', 'TFT Display'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=RSV4'
    },
    'tuono-v4': {
        brand: 'Aprilia',
        name: 'Tuono V4',
        origin: 'Italy',
        category: 'Naked',
        engine: '1077cc V4',
        power: '175 HP',
        torque: '121 Nm',
        weight: '209 kg',
        topSpeed: '280 km/h',
        price: '$16,999',
        description: 'Naked version of the RSV4 with street-friendly attitude.',
        features: ['APRC Electronics', 'Öhlins Suspension', 'Brembo Brakes', 'Cruise Control'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Tuono+V4'
    },
    'rs-660': {
        brand: 'Aprilia',
        name: 'RS 660',
        origin: 'Italy',
        category: 'Sport',
        engine: '659cc parallel-twin',
        power: '100 HP',
        torque: '67 Nm',
        weight: '183 kg',
        topSpeed: '220 km/h',
        price: '$11,299',
        description: 'Middleweight sportbike with lightweight chassis and modern electronics.',
        features: ['Ride Modes', 'TFT Display', 'Quick Shifter', 'Cornering ABS'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=RS+660'
    },
    'tuareg-660': {
        brand: 'Aprilia',
        name: 'Tuareg 660',
        origin: 'Italy',
        category: 'Adventure',
        engine: '659cc parallel-twin',
        power: '80 HP',
        torque: '70 Nm',
        weight: '204 kg',
        topSpeed: '180 km/h',
        price: '$12,499',
        description: 'Italian adventure bike with sporting character and off-road prowess.',
        features: ['Ride Modes', 'TFT Display', 'Long Travel Suspension', 'Skid Plate'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Tuareg+660'
    },

    // MV Agusta
    'f4': {
        brand: 'MV Agusta',
        name: 'F4',
        origin: 'Italy',
        category: 'Superbike',
        engine: '998cc inline-4',
        power: '205 HP',
        torque: '116 Nm',
        weight: '192 kg',
        topSpeed: '300 km/h',
        price: '$28,998',
        description: 'Exotic Italian superbike - art in motion with breathtaking performance.',
        features: ['Öhlins Suspension', 'Brembo Brakes', 'TFT Display', 'Quick Shifter'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=F4'
    },
    'brutale-1000': {
        brand: 'MV Agusta',
        name: 'Brutale 1000',
        origin: 'Italy',
        category: 'Naked',
        engine: '998cc inline-4',
        power: '208 HP',
        torque: '116.5 Nm',
        weight: '186 kg',
        topSpeed: '290 km/h',
        price: '$29,998',
        description: 'The most powerful production naked bike with Italian styling.',
        features: ['Launch Control', 'Quick Shifter', 'TFT Display', 'Öhlins Smart EC 2.0'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Brutale+1000'
    },
    'superveloce': {
        brand: 'MV Agusta',
        name: 'Superveloce',
        origin: 'Italy',
        category: 'Sport',
        engine: '798cc inline-3',
        power: '147 HP',
        torque: '88 Nm',
        weight: '173 kg',
        topSpeed: '240 km/h',
        price: '$28,498',
        description: 'Retro-futuristic design meets modern performance in this Italian masterpiece.',
        features: ['Carbon Fiber', 'TFT Display', 'Quick Shifter', 'Launch Control'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Superveloce'
    },
    'dragster': {
        brand: 'MV Agusta',
        name: 'Dragster',
        origin: 'Italy',
        category: 'Naked',
        engine: '798cc inline-3',
        power: '140 HP',
        torque: '87 Nm',
        weight: '168 kg',
        topSpeed: '235 km/h',
        price: '$18,998',
        description: 'Aggressive naked with unique styling and triple-cylinder character.',
        features: ['Ride Modes', 'TFT Display', 'Quick Shifter', 'LED Lights'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Dragster'
    }
};
