// Motorcycle data with detailed information
const motorcyclesData = {
    // Honda
    'cbr1000rr-r-fireblade': {
        brand: 'Honda',
        name: 'CBR1000RR-R Fireblade',
        origin: 'Japan',
        category: 'Superbike',
        engine: '999cc inline-4',
        power: '217 HP',
        torque: '113 Nm',
        weight: '201 kg',
        topSpeed: '299 km/h',
        price: '$28,500',
        description: 'The ultimate superbike from Honda, featuring MotoGP-derived technology and race-winning performance.',
        features: ['Ride-by-Wire Throttle', 'Cornering ABS', 'Quick Shifter', 'Öhlins Electronic Suspension'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=CBR1000RR-R'
    },
    'africa-twin': {
        brand: 'Honda',
        name: 'Africa Twin',
        origin: 'Japan',
        category: 'Adventure',
        engine: '1084cc parallel-twin',
        power: '101 HP',
        torque: '105 Nm',
        weight: '226 kg',
        topSpeed: '190 km/h',
        price: '$14,500',
        description: 'Legendary adventure bike designed for both on-road and off-road excellence.',
        features: ['DCT Transmission', 'Cruise Control', 'Apple CarPlay', 'LED Lighting'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Africa+Twin'
    },
    'gold-wing': {
        brand: 'Honda',
        name: 'Gold Wing',
        origin: 'Japan',
        category: 'Touring',
        engine: '1833cc flat-6',
        power: '126 HP',
        torque: '170 Nm',
        weight: '383 kg',
        topSpeed: '210 km/h',
        price: '$23,800',
        description: 'The ultimate luxury touring motorcycle with unmatched comfort and technology.',
        features: ['7-Speed DCT', 'Navigation System', 'Heated Seats', 'Apple CarPlay'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Gold+Wing'
    },
    'cb650r': {
        brand: 'Honda',
        name: 'CB650R',
        origin: 'Japan',
        category: 'Naked',
        engine: '649cc inline-4',
        power: '94 HP',
        torque: '64 Nm',
        weight: '202 kg',
        topSpeed: '210 km/h',
        price: '$8,700',
        description: 'Neo Sports Café styling meets inline-four performance in this modern naked bike.',
        features: ['Slipper Clutch', 'LCD Display', 'LED Lights', 'ABS'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=CB650R'
    },

    // Yamaha
    'yzf-r1': {
        brand: 'Yamaha',
        name: 'YZF-R1',
        origin: 'Japan',
        category: 'Superbike',
        engine: '998cc inline-4',
        power: '200 HP',
        torque: '112.4 Nm',
        weight: '199 kg',
        topSpeed: '299 km/h',
        price: '$17,399',
        description: 'MotoGP technology in a street-legal superbike with crossplane crankshaft.',
        features: ['IMU Electronics', 'Quick Shifter', 'Launch Control', 'Slide Control'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=YZF-R1'
    },
    'mt-09': {
        brand: 'Yamaha',
        name: 'MT-09',
        origin: 'Japan',
        category: 'Naked',
        engine: '889cc inline-3',
        power: '119 HP',
        torque: '93 Nm',
        weight: '189 kg',
        topSpeed: '220 km/h',
        price: '$9,399',
        description: 'The ultimate hyper-naked with triple-cylinder excitement and cutting-edge electronics.',
        features: ['6-Axis IMU', 'Ride Modes', 'TFT Display', 'Quick Shifter'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=MT-09'
    },
    'tenere-700': {
        brand: 'Yamaha',
        name: 'Ténéré 700',
        origin: 'Japan',
        category: 'Adventure',
        engine: '689cc parallel-twin',
        power: '72 HP',
        torque: '68 Nm',
        weight: '204 kg',
        topSpeed: '175 km/h',
        price: '$10,299',
        description: 'Lightweight adventure bike built for serious off-road capability.',
        features: ['Rally-Inspired', 'ABS', 'Long Travel Suspension', 'Off-Road Ready'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Tenere+700'
    },
    'niken': {
        brand: 'Yamaha',
        name: 'NIKEN',
        origin: 'Japan',
        category: 'Sport Touring',
        engine: '847cc inline-3',
        power: '115 HP',
        torque: '87.5 Nm',
        weight: '263 kg',
        topSpeed: '210 km/h',
        price: '$17,099',
        description: 'Revolutionary three-wheel design offering unmatched cornering confidence.',
        features: ['LMW Technology', 'TFT Display', 'Cruise Control', 'Traction Control'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=NIKEN'
    },

    // Ducati
    'panigale-v4': {
        brand: 'Ducati',
        name: 'Panigale V4',
        origin: 'Italy',
        category: 'Superbike',
        engine: '1103cc V4',
        power: '214 HP',
        torque: '124 Nm',
        weight: '198 kg',
        topSpeed: '305 km/h',
        price: '$24,995',
        description: 'Italian superbike excellence with MotoGP-derived V4 engine and stunning design.',
        features: ['Cornering ABS', 'DTC EVO', 'DWC EVO', 'Öhlins Suspension'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Panigale+V4'
    },
    'monster': {
        brand: 'Ducati',
        name: 'Monster',
        origin: 'Italy',
        category: 'Naked',
        engine: '937cc L-twin',
        power: '111 HP',
        torque: '93 Nm',
        weight: '188 kg',
        topSpeed: '210 km/h',
        price: '$11,895',
        description: 'Iconic naked bike with Italian styling and Testastretta engine.',
        features: ['Ride Modes', 'TFT Display', 'LED Lights', 'Quick Shifter'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Monster'
    },
    'multistrada-v4': {
        brand: 'Ducati',
        name: 'Multistrada V4',
        origin: 'Italy',
        category: 'Adventure',
        engine: '1158cc V4',
        power: '170 HP',
        torque: '125 Nm',
        weight: '218 kg',
        topSpeed: '270 km/h',
        price: '$23,295',
        description: 'Sport-touring adventure bike with V4 Granturismo engine and advanced electronics.',
        features: ['Radar Technology', 'Adaptive Cruise', 'Semi-Active Suspension', 'V4 Engine'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Multistrada+V4'
    },
    'scrambler': {
        brand: 'Ducati',
        name: 'Scrambler',
        origin: 'Italy',
        category: 'Scrambler',
        engine: '803cc L-twin',
        power: '73 HP',
        torque: '66.2 Nm',
        weight: '189 kg',
        topSpeed: '180 km/h',
        price: '$9,395',
        description: 'Retro-styled bike with modern technology and Italian charm.',
        features: ['Ride by Wire', 'ABS', 'LED Lights', 'LCD Display'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Scrambler'
    },

    // BMW
    's1000rr': {
        brand: 'BMW',
        name: 'S1000RR',
        origin: 'Germany',
        category: 'Superbike',
        engine: '999cc inline-4',
        power: '205 HP',
        torque: '113 Nm',
        weight: '197 kg',
        topSpeed: '299 km/h',
        price: '$17,895',
        description: 'German precision engineering meets superbike performance.',
        features: ['ShiftCam Technology', 'Dynamic Traction Control', 'ABS Pro', 'Launch Control'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=S1000RR'
    },
    'r1250gs': {
        brand: 'BMW',
        name: 'R1250GS',
        origin: 'Germany',
        category: 'Adventure',
        engine: '1254cc boxer-twin',
        power: '136 HP',
        torque: '143 Nm',
        weight: '249 kg',
        topSpeed: '210 km/h',
        price: '$18,995',
        description: 'The world\'s most popular adventure bike with boxer engine.',
        features: ['ShiftCam', 'Dynamic ESA', 'Connectivity', 'TFT Display'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=R1250GS'
    },
    'm1000rr': {
        brand: 'BMW',
        name: 'M1000RR',
        origin: 'Germany',
        category: 'Superbike',
        engine: '999cc inline-4',
        power: '212 HP',
        torque: '113 Nm',
        weight: '192 kg',
        topSpeed: '306 km/h',
        price: '$33,995',
        description: 'BMW\'s first M-branded motorcycle with race-ready technology.',
        features: ['M Carbon Wheels', 'M GPS Lap Trigger', 'M Winglets', 'M ABS'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=M1000RR'
    },
    'f900r': {
        brand: 'BMW',
        name: 'F900R',
        origin: 'Germany',
        category: 'Naked',
        engine: '895cc parallel-twin',
        power: '105 HP',
        torque: '92 Nm',
        weight: '211 kg',
        topSpeed: '220 km/h',
        price: '$9,495',
        description: 'Dynamic roadster with sporty character and everyday usability.',
        features: ['Ride Modes', 'ABS Pro', 'TFT Display', 'LED Lights'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=F900R'
    },

    // Kawasaki
    'ninja-h2': {
        brand: 'Kawasaki',
        name: 'Ninja H2',
        origin: 'Japan',
        category: 'Superbike',
        engine: '998cc inline-4 supercharged',
        power: '228 HP',
        torque: '141.7 Nm',
        weight: '238 kg',
        topSpeed: '336 km/h',
        price: '$29,500',
        description: 'Supercharged hyperbike pushing the boundaries of performance.',
        features: ['Supercharged Engine', 'Carbon Fiber', 'Launch Control', 'Quick Shifter'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Ninja+H2'
    },
    'z900': {
        brand: 'Kawasaki',
        name: 'Z900',
        origin: 'Japan',
        category: 'Naked',
        engine: '948cc inline-4',
        power: '125 HP',
        torque: '98.6 Nm',
        weight: '210 kg',
        topSpeed: '230 km/h',
        price: '$8,999',
        description: 'Aggressive naked bike with inline-four punch and sharp handling.',
        features: ['Sugomi Design', 'TFT Display', 'Traction Control', 'ABS'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Z900'
    },
    'versys-1000': {
        brand: 'Kawasaki',
        name: 'Versys 1000',
        origin: 'Japan',
        category: 'Adventure',
        engine: '1043cc inline-4',
        power: '120 HP',
        torque: '102 Nm',
        weight: '250 kg',
        topSpeed: '210 km/h',
        price: '$13,099',
        description: 'Sport-adventure bike with inline-four power and touring comfort.',
        features: ['KQS Quick Shifter', 'KIBS ABS', 'Cruise Control', 'TFT Display'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Versys+1000'
    },
    'zx-10r': {
        brand: 'Kawasaki',
        name: 'ZX-10R',
        origin: 'Japan',
        category: 'Superbike',
        engine: '998cc inline-4',
        power: '200 HP',
        torque: '114.9 Nm',
        weight: '206 kg',
        topSpeed: '299 km/h',
        price: '$16,599',
        description: 'World Superbike-winning technology in a production superbike.',
        features: ['Kawasaki Cornering Management', 'Launch Control', 'TFT Display', 'Quick Shifter'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=ZX-10R'
    },

    // Suzuki
    'hayabusa': {
        brand: 'Suzuki',
        name: 'Hayabusa',
        origin: 'Japan',
        category: 'Sport',
        engine: '1340cc inline-4',
        power: '187 HP',
        torque: '150 Nm',
        weight: '264 kg',
        topSpeed: '299 km/h',
        price: '$18,599',
        description: 'Legendary speed icon with third-generation refinement and technology.',
        features: ['Ride Modes', 'Launch Control', 'TFT Display', 'Cruise Control'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Hayabusa'
    },
    'gsx-r1000': {
        brand: 'Suzuki',
        name: 'GSX-R1000',
        origin: 'Japan',
        category: 'Superbike',
        engine: '999cc inline-4',
        power: '202 HP',
        torque: '117.6 Nm',
        weight: '202 kg',
        topSpeed: '299 km/h',
        price: '$14,799',
        description: 'Race-proven superbike with MotoGP technology and aggressive performance.',
        features: ['Bi-Directional Quick Shifter', 'Launch Control', 'Cornering ABS', 'Motion Track'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=GSX-R1000'
    },
    'v-strom-1050': {
        brand: 'Suzuki',
        name: 'V-Strom 1050',
        origin: 'Japan',
        category: 'Adventure',
        engine: '1037cc V-twin',
        power: '107 HP',
        torque: '100 Nm',
        weight: '236 kg',
        topSpeed: '200 km/h',
        price: '$14,299',
        description: 'Versatile adventure bike with V-twin character and touring comfort.',
        features: ['Cruise Control', 'Traction Control', 'TFT Display', 'LED Lights'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=V-Strom+1050'
    },
    'katana': {
        brand: 'Suzuki',
        name: 'Katana',
        origin: 'Japan',
        category: 'Sport',
        engine: '999cc inline-4',
        power: '150 HP',
        torque: '108 Nm',
        weight: '215 kg',
        topSpeed: '260 km/h',
        price: '$13,199',
        description: 'Legendary name returns with modern performance and iconic styling.',
        features: ['Traction Control', 'LCD Display', 'LED Lights', 'ABS'],
        image: 'https://via.placeholder.com/800x450/000/fff?text=Katana'
    }
};
